module.exports = {
    devServer:{
      host:'localhost',
      port:8081,
      proxy:{
        '/api':{
          target:'https://as.llynsyw.cn',
          changeOrigin:true,
          pathRewrite:{
            '/api':'/api'
          }
        }
      },
    },
    productionSourceMap:false,
    chainWebpack:(config)=>{
      config.plugins.delete('prefetch');
    }
  }